CREATE TABLE USERACCOUNT(
    ACCOUNTID NUMERIC(19,0) NOT NULL,
    LOGIN VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    NICKNAME VARCHAR(255) NULL,
    LASTLOGINDATE NUMERIC(19,0) NULL
);
CREATE UNIQUE INDEX PK_ACCOUNT ON USERACCOUNT(ACCOUNTID);
CREATE UNIQUE INDEX K01_ACCOUNT ON USERACCOUNT(LOGIN);
CREATE INDEX K02_ACCOUNT ON USERACCOUNT(NICKNAME);


CREATE TABLE IDGEN(
TABLENAME VARCHAR(255) NOT NULL,
NEXTID NUMERIC(19,0) NOT NULL
);
CREATE UNIQUE INDEX PK_IDGEN ON IDGEN(TABLENAME);