CREATE TABLE Message(
MESSAGEID NUMERIC(19,0) NOT NULL,
PUBLISHERID NUMERIC(19,0) NOT NULL,
PUBLICHDATE NUMERIC(19,0) NOT NULL,
MSGBODY VARCHAR(2000000) NULL
);
CREATE UNIQUE INDEX PK_Message ON Message(MESSAGEID);
CREATE INDEX K01_Message ON Message(PUBLISHERID);
CREATE INDEX K02_Message ON Message(PUBLICHDATE);

CREATE TABLE MSGTAGS(
MSGTAGID NUMERIC(19,0) NOT NULL,
TAGVALUE VARCHAR(511) NOT NULL
);
CREATE UNIQUE INDEX PK_MSGTAGS ON MSGTAGS(MSGTAGID);
CREATE INDEX K01_MSGTAGS ON MSGTAGS(TAGVALUE);

CREATE TABLE MSGTAGREL(
RELATIONID NUMERIC(19,0) NOT NULL,
MSGTAGID NUMERIC(19,0) NOT NULL,
MESSAGEID NUMERIC(19,0) NOT NULL
);
CREATE UNIQUE INDEX PK_MSGTAGREL ON MSGTAGREL(RELATIONID);
CREATE INDEX K01_MSGTAGREL ON MSGTAGREL(MSGTAGID);